### ISSUE TITLE
Mutant alleles get silently parsed as the wildtype

### ISSUE THREAD

**Issue by iskandr** [hammerlab/mhcnames#20]
Seeing `HLA-DRA*01:01/DRB1*01:01 C30S mutant` parsed as `HLA-DRA*01:01/DRB1*01:01` 

@timodonnell  -- worth checking if that is impacting your MHCflurry training data.

**Comment by timodonnell** [comment]
hmm we are dropping alleles with the word "mutant" in them here:
https://github.com/hammerlab/mhcflurry/blob/master/downloads-generation/data_curated/curate.py#L89

but I'm curious if you think there are other cases for class I that I
should handle differently

**Comment by iskandr** [comment]
I think that every mutant allele in IEDB does actually use the word "mutant". 

One other potentially source of error from MHCnames is the conversion of serotypes to (potentially incorrect) genotypes. e.g. "A2" -> "HLA-A0201"
