### ISSUE TITLE
Incorrect parsing of alleles with 3 digit codes (e.g. HLA-A02*123)

### ISSUE THREAD

**Issue by iskandr** [hammerlab/mhcnames#4]
Moving this issue from https://github.com/hammerlab/mhctools/issues/59 by @kippakers:

I'm getting some errors (see hammerlab/topiary#61) from mishandling of alleles that look like:
B15120
A02248

which should be HLA-B*15:120 and HLA-A*02:248, but are being interpreted as HLA-B*151:20 and HLA-A*22:48.

I think this can be fixed by making the regex a bit more complicated: taking the allele code, turning leading 00s into 0s, (for say HLA-A*002:01). After that, making length 5 allele codes into 12:345 rather than 123:45. As far as I can tell, there are no 3 digit allele family names.

Sorry I can't just make a branch and do this, I only barely understand python.

---

I made a small edit which solves my problem, but I think would fail for things like HLA-A*002:01:

alleles.py:

``` python
def parse_allele_name(name, species_prefix=None):
# ... lots more code here ...
    # skip initial separator
    sep, name = _parse_separator(name)
    # if all that's left is e.g. "0201" then only parse the
    # first two digits as the family code
    if len(name) == 4:
        family, name = _parse_numbers(name, max_len=2)
#begin kipp edit
    elif len(name) == 5:
        family = name[:2]
        name = name[2:]
#end kipp edit
```

**Comment by iskandr** [comment]
@kippakers I'm actually confused about the "spec" here (if there is a consistent one). Human alleles seem to follow 2 digits followed by 3 digits but other animals (such as sheep) has 3 digits followed by 2 digits. For example, the following are sheep alleles:
- Ovar-N*50001
- Ovar-N*50101
- Ovar-N*50201
- Ovar-N*50301

I guess I could switch between the two parsing modes on a per-species basis? MHC nomenclature sucks.

**Comment by kippakers** [comment]
Wow, I had no idea.  That's super annoying, but yeah, two modes seems the simplest solution.  Thanks for looking into it.
